export const theme = {
    bigBg: "#ebebeb",
    bigBg1: "#fff",
    moduleBg: "#ffffff",
    moduleBg1:"#ffffff",
    moduleBg2:"#eee",
    moduleBg3:"#eee",
    moduleBg4:"#eee",
    headerBg: "#ffffff",
    headerBg1: "#ff6339",
    headerBg2: "#eee",
    darkBgLine: "#cccccc",
    darkBgLine1:"#eee",
    lightBgLine: "#e5e5e5",
    buttonBorder: "#999",
    bigText: "#000",
    bigText1: "#fff",
    text: "#666",
    text1: "#333",
    cashText:'#999',
    cashText1:'#ff6339',
    cashText2:'#666',
    cashText3:'#eee',
    isUsedColor:'#dd6f6e',
    isUsedColor1:'#999',
    bgColorText:'#fff', //有背景的文字颜色（如红色和绿色背景）
    bgColorText1:'#eee',
    mainOrange: "#ff6339",
    mainOrange2: "#ff6339",
    mainOrange1: "#fff",
    redNum: "#dd5533",
    greenNum: "#669900",
    greenBg:"#96D544",
    iconColor:'#999',
    memberColor:'#EEEEEE',
    greenBar:"#53b900"
}